apiVersion: v1
kind: ConfigMap
metadata:
  name: sumologic-configmap
data:
  fluentdLogs: {{ template "sumologic.fullname" . }}-fluentd-logs
  fluentdMetrics: {{ template "sumologic.fullname" . }}-fluentd-metrics
  fluentdNamespace: {{ .Release.Namespace }}