{{- if and .Values.sumologic.fluentd.autoscaling.enabled}}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "sumologic.fullname" . }}
  labels:
    app: {{ template "sumologic.labels.app" . }}
    {{- include "sumologic.labels.common" . | nindent 4 }}  
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "sumologic.fullname" . }}
  minReplicas: {{ .Values.sumologic.fluentd.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.sumologic.fluentd.autoscaling.maxReplicas }}
  metrics:
    {{- toYaml .Values.sumologic.fluentd.autoscaling.metrics | nindent 4 }}
{{- end }}