{{- if .Values.sumologic.setup }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name:  {{ template "sumologic.fullname" . }}-setup
  {{- if .Values.sumologic.setup.clusterRole.annotations  }}
  annotations:
{{ toYaml .Values.sumologic.setup.clusterRole.annotations | indent 4 }}
  {{- end }}
  labels:
    app: {{ template "sumologic.labels.app" . }}
    {{- include "sumologic.labels.common" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - namespaces
    verbs: ["get", "create", "describe", "patch"]
{{- end }}
