{{- if .Values.sumologic.setupEnabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name:  {{ template "sumologic.fullname" . }}-setup
  {{- if .Values.sumologic.setup.clusterRoleBinding.annotations  }}
  annotations:
{{ toYaml .Values.sumologic.setup.clusterRoleBinding.annotations | indent 4 }}
  {{- end }}
  labels:
    app: {{ template "sumologic.labels.app" . }}
    {{- include "sumologic.labels.common" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "sumologic.fullname" . }}-setup
subjects:
  - kind: ServiceAccount
    name: {{ template "sumologic.fullname" . }}-setup
    namespace: {{ .Release.Namespace }}

{{- end }}
