{{- if .Values.sumologic.setupEnabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "sumologic.fullname" . }}-setup
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: {{ template "sumologic.labels.app" . }}
    {{ template "sumologic.labels.common" . }}
spec:
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ template "sumologic.fullname" . }}-setup
      volumes:
      - name: setup
        configMap:
          name: {{ template "sumologic.fullname" . }}-setup
          defaultMode: 0777
      containers:
      - name:  kubectl
        image: gcr.io/google_containers/kubectl:v1.0.7
        command: ["/kubectl"]
        args: ["proxy", "-p", "8001"]
      - name: setup
        image: test1:latest
        imagePullPolicy: Never
        command: ["/etc/terraform/setup.sh"]
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: setup
          mountPath: /etc/terraform
        env:
        - name: SUMOLOGIC_ACCESSID
          value: {{ required "A valid .Values.sumologic.accessId entry required!" .Values.sumologic.accessId }}
        - name: SUMOLOGIC_ACCESSKEY
          value: {{ required "A valid .Values.sumologic.accessKey entry required!" .Values.sumologic.accessKey }}
        - name: SUMOLOGIC_ENVIRONMENT
          value: us2
{{- end }}