{{- if .Values.sumologic.setup }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "sumologic.fullname" . }}-setup
  namespace: {{ .Release.Namespace }}
  {{- if .Values.sumologic.setup.job.annotations  }}
  annotations:
{{ toYaml .Values.sumologic.setup.job.annotations | indent 4 }}
  {{- end }}
  labels:
    app: {{ template "sumologic.labels.app" . }}
    {{- include "sumologic.labels.common" . | nindent 4 }}
spec:
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ template "sumologic.fullname" . }}-setup
      volumes:
      - name: setup
        configMap:
          name: {{ template "sumologic.fullname" . }}-setup
          defaultMode: 0777
      containers:
      - name: setup
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/etc/terraform/setup.sh"]
        volumeMounts:
        - name: setup
          mountPath: /etc/terraform
        {{- if .Values.sumologic.setup.job.envFromSecret }}
        envFrom:
        - secretRef:
            name: {{ .Values.sumologic.setup.job.envFromSecret }}
        {{ else }}
        env:
        - name: SUMOLOGIC_ACCESSID
          value: {{ required "A valid .Values.sumologic.accessId entry required!" .Values.sumologic.setup.job.accessId }}
        - name: SUMOLOGIC_ACCESSKEY
          value: {{ required "A valid .Values.sumologic.accessKey entry required!" .Values.sumologic.setup.job.accessKey }}
        - name: SUMOLOGIC_BASE_URL
          value: {{ .Values.sumologic.setup.job.endpoint }}
        {{ end }}
{{- end}}
