{{- if .Values.sumologic.setupEnabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name:  {{ template "sumologic.fullname" . }}-setup
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: {{ template "sumologic.labels.app" . }}
    {{ template "sumologic.labels.common" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - namespaces
    verbs: ["get", "create", "describe"]
{{- end }}