prometheus:
  prometheusSpec:
    remoteWrite:
    - url: http://fluentd:9888/prometheus.metrics.state.daemonset
      writeRelabelConfigs:
      - action: keep
        regex: kube-state-metrics;(kube_daemonset_status_current_number_scheduled|kube_daemonset_status_desired_number_scheduled|kube_daemonset_status_number_misscheduled|kube_daemonset_status_number_unavailable|kube_daemonset_metadata_generation)
        sourceLabels: [job, __name__]
    - url: http://fluentd:9888/prometheus.metrics.state.deployment
      writeRelabelConfigs:
      - action: keep
        regex: kube-state-metrics;(kube_deployment_metadata_generation|kube_deployment_spec_paused|kube_deployment_spec_replicas|kube_deployment_status_observed_generation|kube_deployment_spec_strategy_rollingupdate_max_unavailable|kube_deployment_status_replicas_available|kube_deployment_status_replicas_unavailable)
        sourceLabels: [job, __name__]
    - url: http://fluentd:9888/prometheus.metrics.state.node
      writeRelabelConfigs:
      - action: keep
        regex: kube-state-metrics;(kube_node_info|kube_node_spec_unschedulable|kube_node_status_allocatable|kube_node_status_capacity|kube_node_status_condition)
        sourceLabels: [job, __name__]
    - url: http://fluentd:9888/prometheus.metrics.state.pod
      writeRelabelConfigs:
      - action: keep
        regex: kube-state-metrics;(kube_pod_container_info|kube_pod_container_resource_requests|kube_pod_container_resource_limits|kube_pod_container_status_ready|kube_pod_container_status_terminated_reason|kube_pod_container_status_waiting_reason|kube_pod_status_phase)
        sourceLabels: [job, __name__]
    - url: http://fluentd:9888/prometheus.metrics.controller-manager
      writeRelabelConfigs:
      - action: keep
        regex: cloudprovider_.*_api_request_duration_seconds.*
        sourceLabels: [__name__]
    - url: http://fluentd:9888/prometheus.metrics.scheduler
      writeRelabelConfigs:
      - action: keep
        regex: scheduler_e2e_scheduling_latency_microseconds.*|scheduler_binding_latency_microseconds.*|scheduler_scheduling_algorithm_latency_microseconds.*
        sourceLabels: [__name__]
    - url: http://fluentd:9888/prometheus.metrics.apiserver
      writeRelabelConfigs:
      - action: keep
        regex: apiserver;(apiserver_request_count|apiserver_request_latencies.*|etcd_request_cache_get_latencies_summary.*|etcd_request_cache_add_latencies_summary.*)
        sourceLabels: [job, __name__]
    - url: http://fluentd:9888/prometheus.metrics.kubelet
      writeRelabelConfigs:
      - action: keep
        regex: kubelet_docker_operations_errors|kubelet_docker_operations_latency_microseconds.*|kubelet_running_container_count|kubelet_running_pod_count|kubelet_runtime_operations_latency_microseconds.*
        sourceLabels: [__name__]
    - url: http://fluentd:9888/prometheus.metrics.container
      writeRelabelConfigs:
      - action: keep
        regex: container_cpu_load_average_10s|container_cpu_system_seconds_total|container_cpu_usage_seconds_total|container_cpu_cfs_throttled_seconds_total|container_memory_usage_bytes|container_spec_memory_limit_bytes|container_memory_swap|container_spec_memory_swap_limit_bytes|container_spec_memory_reservation_limit_bytes|container_fs_usage_bytes|container_fs_limit_bytes|container_fs_writes_bytes_total|container_fs_reads_bytes_total|container_network_receive_bytes_total|container_network_transmit_bytes_total|container_network_receive_errors_total|container_network_transmit_errors_total
        sourceLabels: [__name__]
    - url: http://fluentd:9888/prometheus.metrics.node
      writeRelabelConfigs:
      - action: keep
        regex: node-exporter;node_load(?:1|5|15)
        sourceLabels: [job, __name__]
    - url: http://fluentd:9888/prometheus.metrics.node
      writeRelabelConfigs:
      - action: keep
        regex: node-exporter;node_cpu_seconds_total
        sourceLabels: [job, __name__]
    - url: http://fluentd:9888/prometheus.metrics.node
      writeRelabelConfigs:
      - action: keep
        regex: node-exporter;node_memory_(?:MemAvailable|MemTotal|Buffers|SwapCached)_bytes
        sourceLabels: [job, __name__]
    - url: http://fluentd:9888/prometheus.metrics.node
      writeRelabelConfigs:
      - action: keep
        regex: node-exporter;node_ipvs_(?:incoming|outgoing)_(?:bytes|packets)_total
        sourceLabels: [job, __name__]
    - url: http://fluentd:9888/prometheus.metrics.node
      writeRelabelConfigs:
      - action: keep
        regex: node-exporter;node_disk_(?:(?:reads|writes)_completed|(?:read|written)_bytes)_total
        sourceLabels: [job, __name__]
    - url: http://fluentd:9888/prometheus.metrics.node
      writeRelabelConfigs:
      - action: keep
        regex: node-exporter;node_filesystem_(?:avail|free|size)_bytes
        sourceLabels: [job, __name__]
    - url: http://fluentd:9888/prometheus.metrics.go
      writeRelabelConfigs:
      - action: keep
        regex: go_gc_duration_seconds|go_threads|go_goroutines
        sourceLabels: [__name__]
