apiVersion: v1
kind: Secret
metadata:
  name: sumologic
  namespace: sumologic
  labels:
    k8s-app: fluentd-sumologic
type: Opaque
data:
  # value is base-64 encoded, using following command to get it
  #   echo -n 'plaintext' | base64
  endpoint-metrics: XXXX
